#!/bin/sh

OWNERNAME="therealsaumil"
IMAGENAME="ph0wn"
TAGNAME="10-2024"
VOL="ph0wnvol"

# check if the volume exists, otherwise refuse to build. It doesn't
# matter really, but nice to ensure that the volume is built, to prevent
# later errors.

CHECKVOL=$(docker volume inspect ${VOL} -f '{{.Name}}')
if [ "$CHECKVOL" != "$VOL" ]
then
   echo "Docker volume $VOL needs to be created."
   echo "Please run ./build-ph0wn-volume first."
   exit
fi

DOCKER_BUILDKIT=1 docker build -t $OWNERNAME/$IMAGENAME:$TAGNAME \
                               -f Dockerfile-ph0wn .
