#!/bin/bash

OWNERNAME="therealsaumil"
IMAGENAME="ph0wn"
TAGNAME="10-2024"
VOL="ph0wnvol"
PORTSTRING=""

if [ "${PORTFWD}" = "" ]
then
   PORTFWD="9123:8080"
fi

PORTFWD=$(echo ${PORTFWD} | tr -cd [0-9,:])

IFS=',' read -ra PORTLIST <<< "${PORTFWD}"
for PORTPAIR in "${PORTLIST[@]}"
do
   SPORT=$(echo ${PORTPAIR} | cut -d':' -f1)
   PORTSTRING="${PORTSTRING} -p ${SPORT}:${SPORT}"
done

docker run \
	-it \
	${PORTSTRING} \
	-e PORTFWD="${PORTFWD}" \
	--rm \
	--cap-add=NET_ADMIN \
	--cap-add=SYS_ADMIN \
	--security-opt apparmor=unconfined \
	--device=/dev/net/tun \
	--name ph0wn-docker \
	--mount "type=volume,src=${VOL},dst=/arm64fs" \
	--mount "type=bind,src=$(pwd)/shared,dst=/home/r0/shared" \
	$OWNERNAME/$IMAGENAME:$TAGNAME $*
