#!/bin/bash
echo "Interface: eth0"
echo "        Mode: Static"
echo "        IP: 192.168.100.150"
echo "        Netmask: 255.255.255.0"
echo "        Gateway: 192.168.100.1"
echo "        DNS Server: 192.168.100.1"
