#include <stdio.h>
#include <string.h>
#include <stdlib.h>

char minuscule[] = "abcdefghijklmnopqrstuvwxyz";
char chiffre[] = "0123456789";
char signe[] = "{}";
char password[] = "ph0wn{8c14d876907759e705b9f0e0eacfce1e}";


char *make_pass() {
  char *pass = (char *) malloc(strlen(password)+1);
  if (pass == NULL) {
    printf("Bad malloc\n");
    exit(EXIT_FAILURE);
  }

  /* generated by generate-pass.py */
  pass[0] = minuscule[15];
  pass[1] = minuscule[7];
  pass[2] = chiffre[0];
  pass[3] = minuscule[22];
  pass[4] = minuscule[13];
  pass[5]= signe[0];
  pass[6] = chiffre[8];
  pass[7] = minuscule[2];
  pass[8] = chiffre[1];
  pass[9] = chiffre[4];
  pass[10] = minuscule[3];
  pass[11] = chiffre[8];
  pass[12] = chiffre[7];
  pass[13] = chiffre[6];
  pass[14] = chiffre[9];
  pass[15] = chiffre[0];
  pass[16] = chiffre[7];
  pass[17] = chiffre[7];
  pass[18] = chiffre[5];
  pass[19] = chiffre[9];
  pass[20] = minuscule[4];
  pass[21] = chiffre[7];
  pass[22] = chiffre[0];
 pass[23] = chiffre[5];
 pass[24] = minuscule[1];
 pass[25] = chiffre[9];
 pass[26] = minuscule[5];
 pass[27] = chiffre[0];
 pass[28] = minuscule[4];
 pass[29] = chiffre[0];
 pass[30] = minuscule[4];
 pass[31] = minuscule[0];
 pass[32] = minuscule[2];
 pass[33] = minuscule[5];
 pass[34] = minuscule[2];
 pass[35] = minuscule[4];
 pass[36] = chiffre[1];
 pass[37] = minuscule[4];
 pass[38]= signe[1];

 return pass;
  
}

int main(int argc, char **argv) {
  char * thepass = make_pass();
  if (strcmp(thepass, password) ==0) {
    printf("GOOD\n");
  } else {
    printf("BAD\n");
  }
  free(thepass);
  
  return EXIT_SUCCESS;
}
