# GPIO and SPI
CONFIG_GPIO=y
CONFIG_SPI=y

# Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# CC1101 driver
CONFIG_CC1101=y
CONFIG_CC1101_RX_STACK_SIZE=2048

# Display
CONFIG_DISPLAY=y
CONFIG_HEAP_MEM_POOL_SIZE=16384
