#include <WiFi.h>

char ssid[] = "ph0wnArduino";     //  your network SSID (name)
char stage1[] = "Stage1 flag: ph0wn{WeHopeYouLikeAVR}";   // simple stage1 flag
char minuscule[] = "abcdefghijklmnopqrstuvwxyz";
char chiffre[] = "0123456789";
char signe[] = "{}";

int status = WL_IDLE_STATUS;     // the Wifi radio's status

void setup() {
  char pass[39]; // your network password
  
  // initialize serial:
  Serial.begin(9600);
  Serial.println("Smart B33r challenge v1.4");

  // attempt to connect using WPA2 encryption:
  Serial.println("Attempting to connect to WPA2 wifi with stage1 pass...");
  status = WiFi.begin(ssid, stage1);

  if ( status != WL_CONNECTED) {
    // no wifi, so normally we'll get here!

    Serial.println("Stage 2: find the other flag!");
    Serial.println("[-] Attempting to connect with stage2 pass...");
    
    // password - generated by password.c
    pass[0] = minuscule[15];
    pass[1] = minuscule[7];
    pass[2] = chiffre[0];
    pass[3] = minuscule[22];
    pass[4] = minuscule[13];
    pass[5]= signe[0];
    pass[6] = chiffre[8];
    pass[7] = minuscule[2];
    pass[8] = chiffre[1];
    pass[9] = chiffre[4];
    pass[10] = minuscule[3];
    pass[11] = chiffre[8];
    pass[12] = chiffre[7];
    pass[13] = chiffre[6];
    pass[14] = chiffre[9];
    pass[15] = chiffre[0];
    pass[16] = chiffre[7];
    pass[17] = chiffre[7];
    pass[18] = chiffre[5];
    pass[19] = chiffre[9];
    pass[20] = minuscule[4];
    pass[21] = chiffre[7];
    pass[22] = chiffre[0];
    pass[23] = chiffre[5];   
    pass[24] = minuscule[1];
    pass[25] = chiffre[9];
    pass[26] = minuscule[5];
    pass[27] = chiffre[0];
    pass[28] = minuscule[4];
    pass[29] = chiffre[0];
    pass[30] = minuscule[4];
    pass[31] = minuscule[0];
    pass[32] = minuscule[2];
    pass[33] = minuscule[5];
    pass[34] = minuscule[2];
    pass[35] = minuscule[4];
    pass[36] = chiffre[1];
    pass[37] = minuscule[4];
    pass[38]= signe[1];
  
    status = WiFi.begin(ssid, pass);

    // if you're not connected, stop here:
    if ( status != WL_CONNECTED) {
      Serial.println("[-] Not connected to wifi");
      while(true);
    }
    // if you are connected, print out info about the connection:
    else {
      Serial.println("[+] Connected to wifi with stage 2 pass");
    }
  }
  // if you are connected, print out info about the connection:
  else {
    Serial.println("[+] Connected to wifi with stage 1 pass");
  }
  
}

void loop() {
  // do nothing
}

