FROM alpine

RUN apk update && apk add socat gcc musl-dev libffi-dev openssl-dev python3-dev
RUN apk add --update py-pip
RUN pip install pycryptodome

RUN adduser --disabled-password ctf
WORKDIR /app
COPY logging.py ./
EXPOSE 12345
USER ctf

CMD socat TCP-LISTEN:12345,reuseaddr,fork exec:"timeout 600 python3.9 -u logging.py"
