FROM alpine

RUN apk update && apk add socat gcc musl-dev libffi-dev openssl-dev python3-dev
RUN apk add --update py-pip
RUN pip install pycryptodome

RUN adduser --disabled-password ctf
WORKDIR /app
COPY server.py register.py utils.py ascii_art.py ./
EXPOSE 12346
USER ctf

CMD socat TCP-LISTEN:12346,reuseaddr,fork exec:"timeout 600 python3.9 -u server.py"
