CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_REBOOT=y

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_PRINTK=y
CONFIG_BOOT_BANNER=n
CONFIG_SHELL_PROMPT_UART="$"
CONFIG_SHELL_MINIMAL=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_SHELL_HISTORY=y

CONFIG_USB_CDC_ACM=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_USB_DEVICE_PRODUCT="SPLOOSH"
CONFIG_USB_DEVICE_MANUFACTURER="KABOOM"
CONFIG_USB_DEVICE_PID=0x1d50
CONFIG_USB_DEVICE_VID=0x1915
CONFIG_USB_DEVICE_SN="20250314"

CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY=99

CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_DISPLAY=y
CONFIG_ST7789V=y
CONFIG_ST7789V_RGB565=y

CONFIG_MIPI_DBI=y
CONFIG_MIPI_DBI_SPI=y
CONFIG_LV_Z_BITS_PER_PIXEL=16
CONFIG_LV_COLOR_16_SWAP=y

CONFIG_INPUT=y
CONFIG_INPUT_XPT2046=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=32768

CONFIG_LV_Z_MEM_POOL_SIZE=32768
CONFIG_LVGL=y
CONFIG_LV_USE_LOG=n
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_MONKEY=n
CONFIG_LV_FONT_MONTSERRAT_18=y
CONFIG_LV_COLOR_DEPTH_16=y

CONFIG_LOG=n
CONFIG_ASSERT=n
CONFIG_LV_LOG_LEVEL_INFO=n

CONFIG_STACK_SENTINEL=n
CONFIG_THREAD_STACK_INFO=y
