#!/usr/bin/perl

open(OUTPUT, "> fsdata.c");

chdir("fs");
open(FILES, "find . -type f |");

print(OUTPUT "#include \"lwip/apps/fs.h\"\n#include \"lwip/def.h\"\n\n#ifndef FS_FILE_FLAGS_HEADER_INCLUDED\n#define FS_FILE_FLAGS_HEADER_INCLUDED 1\n#endif\n#ifndef FS_FILE_FLAGS_HEADER_PERSISTENT\n#define FS_FILE_FLAGS_HEADER_PERSISTENT 0\n#endif\n\n");

while($file = <FILES>) {

    # Do not include files in CVS directories nor backup files.
    if($file =~ /(CVS|~)/) {
    	next;
    }
    
    chop($file);
    
    open(HEADER, "> /tmp/header") || die $!;
    if($file =~ /404/) {
	print(HEADER "HTTP/1.0 404 File not found\n");
    } else {
	print(HEADER "HTTP/1.0 200 OK\n");
    }
    print(HEADER "Server: lwIP/pre-0.6 (http://www.sics.se/~adam/lwip/)\n");
    if($file =~ /\.html$/) {
	print(HEADER "Content-type: text/html\n");
    } elsif($file =~ /\.shtml$/) {
	print(HEADER "Content-type: text/html\n");
    } elsif($file =~ /\.gif$/) {
	print(HEADER "Content-type: image/gif\n");
    } elsif($file =~ /\.png$/) {
	print(HEADER "Content-type: image/png\n");
    } elsif($file =~ /\.jpg$/) {
	print(HEADER "Content-type: image/jpeg\n");
    } elsif($file =~ /\.class$/) {
	print(HEADER "Content-type: application/octet-stream\n");
    } elsif($file =~ /\.ram$/) {
	print(HEADER "Content-type: audio/x-pn-realaudio\n");    
    } elsif($file =~ /\.css$/) {
	print(HEADER "Content-type: text/css\n");    
    } else {
	print(HEADER "Content-type: text/plain\n");
    }
    print(HEADER "\n");
    close(HEADER);

    unless($file =~ /\.plain$/ || $file =~ /cgi/) {
	system("cat /tmp/header $file > /tmp/file");
    } else {
	system("cp $file /tmp/file");
    }
    
    open(FILE, "/tmp/file");
    unlink("/tmp/file");
    unlink("/tmp/header");

    $file =~ s/\.//;
    $fvar = $file;
    $fvar =~ s-/-_-g;
    $fvar =~ s-\.-_-g;
    print(OUTPUT "static const unsigned char data".$fvar."[] = {\n");
    print(OUTPUT "\t/* $file */\n\t");
    for($j = 0; $j < length($file); $j++) {
	printf(OUTPUT "%#02x, ", unpack("C", substr($file, $j, 1)));
    }
    printf(OUTPUT "0,\n");
    
    
    $i = 0;
    while(read(FILE, $data, 1)) {
        if($i == 0) {
            print(OUTPUT "\t");
        }
        printf(OUTPUT "%#02x, ", unpack("C", $data));
        $i++;
        if($i == 10) {
            print(OUTPUT "\n");
            $i = 0;
        }
    }
    print(OUTPUT "};\n\n");
    close(FILE);
    push(@fvars, $fvar);
    push(@files, $file);
}

for($i = 0; $i < @fvars; $i++) {
    $file = $files[$i];
    $fvar = $fvars[$i];

    if($i == 0) {
        $prevfile = "NULL";
    } else {
        $prevfile = "file" . $fvars[$i - 1];
    }
    print(OUTPUT "const struct fsdata_file file".$fvar."[] = {{$prevfile, data$fvar, ");
    print(OUTPUT "data$fvar + ". (length($file) + 1) .", ");
    #print(OUTPUT "sizeof(data$fvar) - ". (length($file) + 1) ."}};\n\n");
    print(OUTPUT "sizeof(data$fvar) - ". (length($file) + 1) .", ");
    print(OUTPUT "FS_FILE_FLAGS_HEADER_INCLUDED | FS_FILE_FLAGS_HEADER_PERSISTENT ");
    if($file =~ /\.shtml$/) {print(OUTPUT "| FS_FILE_FLAGS_SSI");}
    print(OUTPUT "}};\n\n");

}

print(OUTPUT "#define FS_ROOT file$fvars[$i - 1]\n\n");
print(OUTPUT "#define FS_NUMFILES $i\n");
