#!/bin/sh
CNAME="trail-server"

# check if container is running
RUNNING=$(docker ps --format '{{.Names}}' | grep ${CNAME})
if [ "${RUNNING}" != "${CNAME}" ]
then
   echo "${CNAME}: container not running"
   exit
fi

docker exec -it ${CNAME} /opt/arm64halt
