version: "3"
services:
  server:
    build: server/
    command: python3 server.py
    ports:
      - 1234:1234
  client:
    build: client/
    command: python3 client.py
    ports:
      - 1233:1233
    depends_on:
      - server
    environment:
      - SERVER_HOSTNAME=server
    links:
      - "server"
